### ISSUE TITLE
Glide 3.6.1

### ISSUE THREAD

**Issue by pablode** [florent37/GlidePalette#1]
It seems like Glide has updated to version [`3.6.1`](https://github.com/bumptech/glide/releases) instead of the expected version [`3.6.0`](https://github.com/florent37/GlidePalette/blob/master/glidepalette/build.gradle#L29)

~~I suppose this is the reason why this is not working: [..]~~
Edit: messed that up, thanks for the helpful answer.

**Comment by TWiStErRob** [comment]
There are no breaking changes when minor version increases.

The problem is that you're using `Uri albumArtUri` and `GlidePalette.with` only supports `String` models. If you read the message you can see that it wants `RequestListener<Uri, GlideDrawable>`, but receives a `GlidePalette`, which [implements `RequestListener<String, GlideDrawable>`](https://github.com/florent37/GlidePalette/blob/master/glidepalette/src/main/java/com/github/florent37/glidepalette/GlidePalette.java#L14)
